site_name: Go Training Exercises
site_description: A collection of exercises for Go beginners
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy

nav:
  - Home: index.md
  - HTTP Basics:
    - Introduction to net/http: http/introduction.md
    - Making HTTP Requests: http/making-requests.md
    - Struct Tags: http/struct-tags.md
    - Parsing JSON Responses: http/parsing-json.md
    - HTTP Client Example: http/http-client-example.md
    - JSON Parsing Example: http/json-parsing-example.md
    - Exercises: http/exercises.md
  - Testing:
    - Overview: testing/index.md
    - Basic Unit Tests: testing/basic-unit-tests.md
    - Table-Driven Tests: testing/table-driven-tests.md
    - Running Tests: testing/running-tests.md
    - Exercises: testing/exercises.md
  - CLI with Cobra:
    - Overview: cli/index.md
    - Basic Usage: cli/basic-usage.md
    - Advanced Usage: cli/advanced-usage.md
    - Exercises: cli/exercises.md
  - gRPC:
    - Overview: grpc/index.md
    - Introduction to gRPC: grpc/introduction.md
    - Protocol Buffers: grpc/protobuf.md
    - Server-Client Example: grpc/server-client-example.md
    - Exercises: grpc/exercises.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - admonition
  - pymdownx.details
